README.md, bin/cli.js, index.js, package.json, test/example/onlyRealDeps/a.js, test/test.js
Integrates filing-cabinet to handle automatic partial resolution based on various languages and module formats.
Breaking: Moves to an object form api to support new and future configuration values alongside optional args.
Ref #23
Fixes #24, Fixes #19, Fixes #22
=> Filing cabinet

package.json, test/test.js
Refs https://github.com/dependents/node-precinct/pull/30
=> CJS/ES6: Tests for lazy requires and precinct bump

index.js, lib/Config.js, test/test.js
Refs https://github.com/dependents/node-dependency-tree/pull/58
=> Backfill a test for the clone bug

README.md, package.json, test/test.js
Refs https://github.com/dependents/node-filing-cabinet/pull/31
Refs https://github.com/dependents/node-precinct/pull/34
=> Less support

package.json
Refs https://github.com/dependents/node-filing-cabinet/pull/32
=> Bump cabinet

package.json, test/test.js
Refs dependents/node-precinct#37
=> Bump deps for dynamic import support

bin/cli.js, index.js, lib/Config.js, webpack.config.js
Nothing major but `removeDups` got eliminated.
=> Make use of ES2015 features

README.md, package-lock.json, package.json
references https://github.com/dependents/node-precinct/pull/40
=> chore: bump precinct version

.babelrc, package-lock.json, package.json
Including updating babel to version 7
=> Update most dev-dependencies

package-lock.json, package.json
This PR doesn't go into master but into #86 to fix some test failures. Unfortunately not fixing all of them.
=> Update more deps to fix some test failures

.travis.yml, package-lock.json, package.json, test/example/extended/a.js, test/example/extended/b.js, test/example/extended/c.js, test/example/ts/a.ts, test/example/ts/b.ts, test/example/ts/c.ts, test/test.js
=> Fix tests and bump deps

index.js
Make the code quite a bit easier to follow :)
More could be done by changing the public API but I'm not sure if it's worth the breaking change. (even though the next version will be a major one)
=> Use Set as the internal datastructure when using the list form

README.md, index.js, lib/Config.js, package-lock.json, package.json, test/example/ts/.tsconfig, test/test.js
Refs pahen/madge#184
Refs pahen/madge#167
Refs pahen/madge#179
Refs https://github.com/dependents/node-filing-cabinet/pull/64
=> Support a tsconfig

package-lock.json, package.json, test/example/ts/d.tsx, test/test.js
Refs https://github.com/pahen/madge/issues/189
Refs https://github.com/dependents/node-precinct/pull/54
Refs https://github.com/dependents/node-filing-cabinet/pull/73
=> Support for tsx

package-lock.json, package.json
Refs https://github.com/dependents/node-dependency-tree/issues/101
=> Bump precinct for TS fix

package-lock.json, package.json
Refs dependents/node-filing-cabinet#77
=> Bump filing cabinet for TS resolution fix

.npmignore, package-lock.json, package.json, test/test.js
=> Clean up the published contents

package-lock.json, package.json, test/example/ts/mixedTsJs/.tsconfig, test/example/ts/mixedTsJs/a.js, test/example/ts/mixedTsJs/b.ts, test/test.js
You need to make sure you have a TS config that has the allowJS compiler option turned on.
Fixes https://github.com/dependents/node-dependency-tree/issues/104
=> Test to prove that mixing ts imports in a js file works

package-lock.json, package.json
Updated `precinct` to latest version `^9.0.0`
Updated `typescript` to latest version `4.9.4`
=> upgrade `precinct` and `typescript`

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/lint.yml, .npmrc, bin/cli.js, package-lock.json, package.json, test/test.mjs
=> Update dependencies and drop Node.js < 18 support
